# Generated by Django 4.2.10 on 2026-03-31 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtisanRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Poor"),
                            (2, "⭐⭐ Fair"),
                            (3, "⭐⭐⭐ Good"),
                            (4, "⭐⭐⭐⭐ Very Good"),
                            (5, "⭐⭐⭐⭐⭐ Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artisan",
                    models.ForeignKey(
                        limit_choices_to={"is_artisan": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artisan_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artisan_ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="artisanrating",
            constraint=models.UniqueConstraint(
                fields=["artisan", "rater"], name="unique_artisan_rater_rating"
            ),
        ),
    ]
