# Generated by Django 4.2.10 on 2026-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_artisanrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency_code",
            field=models.CharField(
                default="USD",
                help_text="Currency code (USD, EUR, XAF, NGN, GHS, KES, ZAR, EGP, MAD, GBP)",
                max_length=3,
            ),
        ),
    ]
