# Generated by Django 4.2.10 on 2026-03-31 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0004_product_currency_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artisanrating",
            name="unique_artisan_rater_rating",
        ),
        migrations.AlterField(
            model_name="product",
            name="currency_code",
            field=models.CharField(
                choices=[
                    ("USD", "USD - US Dollar"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound"),
                    ("XAF", "XAF - CFA Franc (Central)"),
                    ("NGN", "NGN - Nigerian Naira"),
                    ("GHS", "GHS - Ghanaian Cedi"),
                    ("KES", "KES - Kenyan Shilling"),
                    ("ZAR", "ZAR - South African Rand"),
                    ("EGP", "EGP - Egyptian Pound"),
                    ("MAD", "MAD - Moroccan Dirham"),
                ],
                default="USD",
                help_text="Currency code (USD, EUR, XAF, NGN, GHS, KES, ZAR, EGP, MAD, GBP)",
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artisanrating",
            unique_together={("artisan", "rater")},
        ),
    ]
