# Generated by Django 4.2.10 on 2026-03-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("customer", "Customer"), ("artisan", "Artisan/Seller")],
                default="customer",
                help_text="User role in the marketplace",
                max_length=10,
            ),
        ),
    ]
