# Generated by Django 6.0.3 on 2026-03-18 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangerate',
            name='unique_currency_rate_per_date',
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If False, this currency is hidden from the selector'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_to_usd',
            field=models.DecimalField(decimal_places=8, help_text='Value of 1 unit of this currency expressed in USD', max_digits=18),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_in_currency',
            field=models.DecimalField(decimal_places=2, help_text='Amount the customer paid in their chosen currency', max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_in_usd',
            field=models.DecimalField(decimal_places=2, help_text='Equivalent amount in USD for reporting (computed at payment time)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the payment was initiated'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(help_text='Currency the customer chose at checkout', on_delete=django.db.models.deletion.PROTECT, to='payments.currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.IntegerField(help_text="ID of the order being paid (from Randy's orders.Order model)"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, default='', help_text='External reference (e.g. from payment gateway)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last status update'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='event_type',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], help_text='What kind of event occurred', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional info (error messages, gateway response, etc.)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this event occurred'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency', 'date_updated')},
        ),
    ]
