# Generated by Django 4.2.10 on 2026-03-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_artisanprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="artisanprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Description of your artisan work and experience",
            ),
        ),
        migrations.AlterField(
            model_name="artisanprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="artisans/"),
        ),
    ]
