# Generated by Django 4.2.10 on 2026-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_artisanprofile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="artisanprofile",
            name="currency_preference",
            field=models.CharField(
                choices=[
                    ("USD", "USD - US Dollar"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound"),
                    ("XAF", "XAF - CFA Franc (Central)"),
                    ("NGN", "NGN - Nigerian Naira"),
                    ("GHS", "GHS - Ghanaian Cedi"),
                    ("KES", "KES - Kenyan Shilling"),
                    ("ZAR", "ZAR - South African Rand"),
                    ("EGP", "EGP - Egyptian Pound"),
                    ("MAD", "MAD - Moroccan Dirham"),
                ],
                default="USD",
                help_text="Your default currency for displaying dashboard values",
                max_length=3,
            ),
        ),
    ]
