# Generated by Django 6.0.3 on 2026-04-09 07:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_wallet_transaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("mtn", "MTN Mobile Money"),
                            ("orange", "Orange Money"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True, help_text="For bank transfer", max_length=255
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, help_text="For bank transfer", max_length=50
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True, help_text="For MTN/Orange Money", max_length=20
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "amount_after_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artisan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="accounts.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal Request",
                "verbose_name_plural": "Withdrawal Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "collected_from",
                    models.CharField(
                        help_text="Artisan username for reference", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "withdrawal_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_tax",
                        to="accounts.withdrawalrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Tax",
                "verbose_name_plural": "Admin Taxes",
                "ordering": ["-created_at"],
            },
        ),
    ]
