# Generated by Django 6.0.3 on 2026-04-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_withdrawalrequest_admintax"),
    ]

    operations = [
        migrations.AddField(
            model_name="artisanprofile",
            name="social_links",
            field=models.JSONField(
                blank=True, default=dict, help_text="Social media links as JSON"
            ),
        ),
    ]
